# Версии зависимостей — меняем только здесь
springBootVersion=3.3.13
dependencyManagementVersion=1.1.6
springCloudVersion=2023.0.5
jjwtVersion=0.12.6
mapstructVersion=1.6.2
lombokVersion=1.18.34
lombokMapstructBindingVersion=0.2.0
springdocVersion=2.6.0

org.gradle.jvmargs=-Xmx1g -Dfile.encoding=UTF-8
