--liquibase formatted sql

--changeset sergey:004-seed-system-exercises
-- Стартовый каталог системных упражнений (owner_id = NULL).
INSERT INTO exercises (name, body_part, equipment, tracking_type, icon)
VALUES
    ('Жим лёжа', 'CHEST', 'BARBELL', 'WEIGHT_REPS', 'barbell'),
    ('Жим лёжа на наклонной скамье', 'CHEST', 'BARBELL', 'WEIGHT_REPS', 'barbell'),
    ('Жим гантелей лёжа', 'CHEST', 'DUMBBELL', 'WEIGHT_REPS', 'dumbbell'),
    ('Разводка гантелей', 'CHEST', 'DUMBBELL', 'WEIGHT_REPS', 'dumbbell'),
    ('Отжимания на брусьях', 'CHEST', 'BODYWEIGHT', 'WEIGHT_REPS', 'bodyweight'),
    ('Отжимания от пола', 'CHEST', 'BODYWEIGHT', 'WEIGHT_REPS', 'bodyweight'),
    ('Становая тяга', 'BACK', 'BARBELL', 'WEIGHT_REPS', 'barbell'),
    ('Подтягивания', 'BACK', 'BODYWEIGHT', 'WEIGHT_REPS', 'bodyweight'),
    ('Тяга штанги в наклоне', 'BACK', 'BARBELL', 'WEIGHT_REPS', 'barbell'),
    ('Тяга гантели одной рукой', 'BACK', 'DUMBBELL', 'WEIGHT_REPS', 'dumbbell'),
    ('Тяга верхнего блока', 'BACK', 'MACHINE', 'WEIGHT_REPS', 'machine'),
    ('Гиперэкстензия', 'BACK', 'BODYWEIGHT', 'WEIGHT_REPS', 'bodyweight'),
    ('Приседания со штангой', 'LEGS', 'BARBELL', 'WEIGHT_REPS', 'barbell'),
    ('Жим ногами', 'LEGS', 'MACHINE', 'WEIGHT_REPS', 'machine'),
    ('Румынская тяга', 'LEGS', 'BARBELL', 'WEIGHT_REPS', 'barbell'),
    ('Выпады с гантелями', 'LEGS', 'DUMBBELL', 'WEIGHT_REPS', 'dumbbell'),
    ('Сгибание ног в тренажёре', 'LEGS', 'MACHINE', 'WEIGHT_REPS', 'machine'),
    ('Подъём на носки', 'LEGS', 'MACHINE', 'WEIGHT_REPS', 'machine'),
    ('Бег', 'LEGS', 'BODYWEIGHT', 'DISTANCE', 'run'),
    ('Жим штанги стоя', 'SHOULDERS', 'BARBELL', 'WEIGHT_REPS', 'barbell'),
    ('Жим гантелей сидя', 'SHOULDERS', 'DUMBBELL', 'WEIGHT_REPS', 'dumbbell'),
    ('Махи гантелями в стороны', 'SHOULDERS', 'DUMBBELL', 'WEIGHT_REPS', 'dumbbell'),
    ('Махи в наклоне', 'SHOULDERS', 'DUMBBELL', 'WEIGHT_REPS', 'dumbbell'),
    ('Подъём штанги на бицепс', 'ARMS', 'BARBELL', 'WEIGHT_REPS', 'barbell'),
    ('Молотки с гантелями', 'ARMS', 'DUMBBELL', 'WEIGHT_REPS', 'dumbbell'),
    ('Французский жим', 'ARMS', 'BARBELL', 'WEIGHT_REPS', 'barbell'),
    ('Разгибание рук на блоке', 'ARMS', 'MACHINE', 'WEIGHT_REPS', 'machine'),
    ('Планка', 'CORE', 'BODYWEIGHT', 'TIME', 'bodyweight'),
    ('Скручивания', 'CORE', 'BODYWEIGHT', 'WEIGHT_REPS', 'bodyweight'),
    ('Подъём ног в висе', 'CORE', 'BODYWEIGHT', 'WEIGHT_REPS', 'bodyweight');

-- Мышцы привязываем по названию: id упражнений генерирует БД, заранее мы их не знаем.
-- VALUES (...) AS m(...) — "виртуальная таблица" прямо в запросе, её JOIN-им с exercises.
INSERT INTO exercise_muscles (exercise_id, muscle, role)
SELECT e.id, m.muscle, m.role
FROM (VALUES
    ('Жим лёжа', 'CHEST', 'PRIMARY'),
    ('Жим лёжа', 'FRONT_DELTS', 'SECONDARY'),
    ('Жим лёжа', 'TRICEPS', 'SECONDARY'),
    ('Жим лёжа на наклонной скамье', 'CHEST', 'PRIMARY'),
    ('Жим лёжа на наклонной скамье', 'FRONT_DELTS', 'SECONDARY'),
    ('Жим лёжа на наклонной скамье', 'TRICEPS', 'SECONDARY'),
    ('Жим гантелей лёжа', 'CHEST', 'PRIMARY'),
    ('Жим гантелей лёжа', 'FRONT_DELTS', 'SECONDARY'),
    ('Жим гантелей лёжа', 'TRICEPS', 'SECONDARY'),
    ('Разводка гантелей', 'CHEST', 'PRIMARY'),
    ('Разводка гантелей', 'FRONT_DELTS', 'SECONDARY'),
    ('Отжимания на брусьях', 'CHEST', 'PRIMARY'),
    ('Отжимания на брусьях', 'TRICEPS', 'PRIMARY'),
    ('Отжимания на брусьях', 'FRONT_DELTS', 'SECONDARY'),
    ('Отжимания от пола', 'CHEST', 'PRIMARY'),
    ('Отжимания от пола', 'TRICEPS', 'SECONDARY'),
    ('Отжимания от пола', 'FRONT_DELTS', 'SECONDARY'),
    ('Становая тяга', 'LOWER_BACK', 'PRIMARY'),
    ('Становая тяга', 'GLUTES', 'PRIMARY'),
    ('Становая тяга', 'HAMSTRINGS', 'PRIMARY'),
    ('Становая тяга', 'TRAPS', 'SECONDARY'),
    ('Становая тяга', 'FOREARMS', 'SECONDARY'),
    ('Подтягивания', 'LATS', 'PRIMARY'),
    ('Подтягивания', 'BICEPS', 'SECONDARY'),
    ('Подтягивания', 'UPPER_BACK', 'SECONDARY'),
    ('Тяга штанги в наклоне', 'UPPER_BACK', 'PRIMARY'),
    ('Тяга штанги в наклоне', 'LATS', 'PRIMARY'),
    ('Тяга штанги в наклоне', 'BICEPS', 'SECONDARY'),
    ('Тяга штанги в наклоне', 'REAR_DELTS', 'SECONDARY'),
    ('Тяга гантели одной рукой', 'LATS', 'PRIMARY'),
    ('Тяга гантели одной рукой', 'UPPER_BACK', 'SECONDARY'),
    ('Тяга гантели одной рукой', 'BICEPS', 'SECONDARY'),
    ('Тяга верхнего блока', 'LATS', 'PRIMARY'),
    ('Тяга верхнего блока', 'BICEPS', 'SECONDARY'),
    ('Гиперэкстензия', 'LOWER_BACK', 'PRIMARY'),
    ('Гиперэкстензия', 'GLUTES', 'SECONDARY'),
    ('Гиперэкстензия', 'HAMSTRINGS', 'SECONDARY'),
    ('Приседания со штангой', 'QUADS', 'PRIMARY'),
    ('Приседания со штангой', 'GLUTES', 'PRIMARY'),
    ('Приседания со штангой', 'ADDUCTORS', 'SECONDARY'),
    ('Приседания со штангой', 'LOWER_BACK', 'SECONDARY'),
    ('Жим ногами', 'QUADS', 'PRIMARY'),
    ('Жим ногами', 'GLUTES', 'SECONDARY'),
    ('Румынская тяга', 'HAMSTRINGS', 'PRIMARY'),
    ('Румынская тяга', 'GLUTES', 'PRIMARY'),
    ('Румынская тяга', 'LOWER_BACK', 'SECONDARY'),
    ('Выпады с гантелями', 'QUADS', 'PRIMARY'),
    ('Выпады с гантелями', 'GLUTES', 'PRIMARY'),
    ('Выпады с гантелями', 'HAMSTRINGS', 'SECONDARY'),
    ('Сгибание ног в тренажёре', 'HAMSTRINGS', 'PRIMARY'),
    ('Подъём на носки', 'CALVES', 'PRIMARY'),
    ('Бег', 'QUADS', 'PRIMARY'),
    ('Бег', 'CALVES', 'SECONDARY'),
    ('Бег', 'HAMSTRINGS', 'SECONDARY'),
    ('Жим штанги стоя', 'FRONT_DELTS', 'PRIMARY'),
    ('Жим штанги стоя', 'SIDE_DELTS', 'SECONDARY'),
    ('Жим штанги стоя', 'TRICEPS', 'SECONDARY'),
    ('Жим гантелей сидя', 'FRONT_DELTS', 'PRIMARY'),
    ('Жим гантелей сидя', 'SIDE_DELTS', 'SECONDARY'),
    ('Жим гантелей сидя', 'TRICEPS', 'SECONDARY'),
    ('Махи гантелями в стороны', 'SIDE_DELTS', 'PRIMARY'),
    ('Махи в наклоне', 'REAR_DELTS', 'PRIMARY'),
    ('Махи в наклоне', 'UPPER_BACK', 'SECONDARY'),
    ('Подъём штанги на бицепс', 'BICEPS', 'PRIMARY'),
    ('Подъём штанги на бицепс', 'FOREARMS', 'SECONDARY'),
    ('Молотки с гантелями', 'BICEPS', 'PRIMARY'),
    ('Молотки с гантелями', 'FOREARMS', 'PRIMARY'),
    ('Французский жим', 'TRICEPS', 'PRIMARY'),
    ('Разгибание рук на блоке', 'TRICEPS', 'PRIMARY'),
    ('Планка', 'ABS', 'PRIMARY'),
    ('Планка', 'OBLIQUES', 'SECONDARY'),
    ('Скручивания', 'ABS', 'PRIMARY'),
    ('Подъём ног в висе', 'ABS', 'PRIMARY'),
    ('Подъём ног в висе', 'OBLIQUES', 'SECONDARY')
) AS m(exercise_name, muscle, role)
JOIN exercises e ON e.name = m.exercise_name AND e.owner_id IS NULL;
--rollback DELETE FROM exercises WHERE owner_id IS NULL;
