// workout-service: Каталог упражнений (+ мышцы, медиа для анимаций), свои упражнения, комплексы, тренировки, подходы.
plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common-lib')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.liquibase:liquibase-core'
    runtimeOnly 'org.postgresql:postgresql'

    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocVersion}"

    implementation "org.mapstruct:mapstruct:${mapstructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
    // чтобы MapStruct "видел" геттеры/сеттеры, сгенерированные Lombok
    annotationProcessor "org.projectlombok:lombok-mapstruct-binding:${lombokMapstructBindingVersion}"

    // --- специфичное для workout-service ---
    // Resource Server: сервис сам НЕ выпускает токены, только проверяет чужие (выпущенные user-service)
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
}
