# Профиль local: запуск из IDEA с -Dspring.profiles.active=local
spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/user_db
    username: ${DB_USERNAME:vegas}
    password: ${DB_PASSWORD:vegas}
